### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by ahmed8aa** [Ahmed8aa/az_sc_tr#5]

**Comment by ahmed8aa** [comment]
@all-contributors please add @OmarElmenofy for design

**Comment by Ahmed8aa** [comment]
@all-contributors
please add @OmarElmenofy for contribution
please add @Boda1515 for contribution

**Comment by Ahmed8aa** [comment]
https://github.com/all-contributors
please add @OmarElmenofy for contribution
please add @Boda1515 for contribution

**Comment by Ahmed8aa** [comment]
@all-contributors
please add @OmarElmenofy for contribution
please add @Boda1515 for contribution

**Comment by ahmed8aa** [comment]
@all-contributors
please add @Boda1515 for code
